bcgov/myhealthBC-android

app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/repository/CardRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/addcard/FetchVaccineCardFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchTravelPassFragment.kt

loaded field in the API response will return false when HGS will respond with cache data.
HGS response also provides the retry time after which updated data will be available.

Retry logic update

---

.gitignore
app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/data/local/entity/HealthCard.kt
app/src/main/java/ca/bc/gov/bchealth/repository/CardRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/mycards/MyCardsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchTravelPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchTravelPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/utils/SHCDecoder.kt
app/src/main/res/layout/fragment_add_card_options.xml
app/src/main/res/layout/scene_mycards_add_card.xml

1. HAPP-235: Replace Vaccine Pass added by Scan / Upload when fetching Federal Pass for that pass
2. HAPP-233 UI support for screens lesser than 4 inch

V1.0.7 bugfix

---

app/src/main/java/ca/bc/gov/bchealth/data/local/dao/CovidTestResultDao.kt
app/src/main/java/ca/bc/gov/bchealth/datasource/LocalDataSource.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/SettingFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/SettingsViewModel.kt
app/src/main/res/layout/fragment_setting.xml
app/src/main/res/values/strings.xml

- added delete all records functionality

Delete all records functionality

---

app/src/main/java/ca/bc/gov/bchealth/repository/CardRepository.kt
app/src/main/java/ca/bc/gov/bchealth/repository/ErrorCodes.kt
app/src/main/java/ca/bc/gov/bchealth/repository/ErrorData.kt
app/src/main/java/ca/bc/gov/bchealth/repository/HealthRecordsRepository.kt
app/src/main/java/ca/bc/gov/bchealth/repository/Response.kt
app/src/main/java/ca/bc/gov/bchealth/ui/addcard/AddCardOptionFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/addcard/AddCardOptionViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/addcard/FetchVaccineCardFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/CovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/FetchCovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/FetchCovidTestResultViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/vaccinerecords/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/vaccinerecords/VaccineDetailsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/scanner/BarcodeScannerFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchTravelPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchTravelPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt
app/src/main/java/ca/bc/gov/bchealth/viewmodel/FetchVaccineDataViewModel.kt
app/src/main/res/values/strings.xml

- bugfix HAPP-270
- code refactoring for showing an alert dialog
- error and response handling classes are moved repository package

Bug fix and code refactoring

---

app/src/main/java/ca/bc/gov/bchealth/data/local/Converters.kt
app/src/main/java/ca/bc/gov/bchealth/data/local/entity/CovidTestResult.kt
app/src/main/java/ca/bc/gov/bchealth/repository/HealthRecordsRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/CovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/FetchCovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt

- bugfixes on Individual health records 
- covid test result api integration.

Bug fixes & Covid test result api integration.

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/FetchCovidTestResultFragment.kt

- added queue.it for fetching covid test result.

Added queue.it for fetching covid test result.

---

app/src/main/java/ca/bc/gov/bchealth/data/local/dao/CovidTestResultDao.kt
app/src/main/java/ca/bc/gov/bchealth/datasource/LocalDataSource.kt
app/src/main/java/ca/bc/gov/bchealth/model/healthrecords/IndividualRecord.kt
app/src/main/java/ca/bc/gov/bchealth/repository/HealthRecordsRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/HealthRecordsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/CovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/CovidTestResultViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/ItemCovidTestResultFragment.kt
app/src/main/res/drawable/default_indicator_dot.xml
app/src/main/res/layout/fragment_covid_test_result.xml
app/src/main/res/layout/item_covid_test_result.xml
app/src/main/res/navigation/bc_vaccine_card_nav_graph.xml

- added different test results for one covid test

Added different test results for one covid test

---

app/src/main/java/ca/bc/gov/bchealth/data/local/dao/CovidTestResultDao.kt
app/src/main/java/ca/bc/gov/bchealth/data/local/entity/CovidTestResult.kt
app/src/main/java/ca/bc/gov/bchealth/repository/HealthRecordsRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt
app/src/main/res/layout/item_health_records_abstract.xml
app/src/main/res/values/strings.xml

- added logic to update pending covid test results

Added logic to update pending covid test results

---

app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt

- updated date format in individual vaccine records screen.

Bugfix HAPP-285

---

app/src/main/java/ca/bc/gov/bchealth/model/ImmunizationStatus.kt
app/src/main/java/ca/bc/gov/bchealth/repository/HealthRecordsRepository.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecords/covidtestresults/ItemCovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt

- bug fixes: HAPP-285, HAPP-286
- updated individual records ui to show test outcome HAPP-290

Bug fix and Individual records UI update

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassesFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/manage/ManageHealthPassFragment.kt

-added swipe to delete functionality on health passes

swipe to delete functionality on health passes

---

app/src/main/java/ca/bc/gov/bchealth/ui/custom/DatePickerExtension.kt
app/src/main/java/ca/bc/gov/bchealth/ui/custom/PHNExtension.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/manage/ManageHealthPassAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/FetchTestRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/SettingsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt
app/src/main/res/layout/fragment_my_cards.xml
app/src/main/res/layout/scene_mycards_add_card.xml
app/src/main/res/layout/scene_mycards_single_card.xml
repository/src/main/java/ca/bc/gov/repository/ClearStorageRepository.kt

-updated fetch covid test form validations
-updated fetch vaccine data form validations
-updated settings screen navigation

Form validations and Settings screen navigation

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/manage/ManageHealthPassFragment.kt
data/src/main/java/ca/bc/gov/data/datasource/PatientWithVaccineRecordLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/local/dao/PatientWithVaccineRecordDao.kt
data/src/main/java/ca/bc/gov/data/local/entity/PatientEntity.kt
data/src/main/java/ca/bc/gov/data/model/mapper/DtoToEntityMapper.kt
repository/src/main/java/ca/bc/gov/repository/PatientWithVaccineRecordRepository.kt

-added reordering of health passes

 Reorder health passes

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassesFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/onboarding/OnBoardingSliderFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/onboarding/OnBoardingSliderViewModel.kt
data/src/main/java/ca/bc/gov/data/local/preference/EncryptedPreferenceStorage.kt
repository/src/main/java/ca/bc/gov/repository/OnBoardingRepository.kt
repository/src/main/java/ca/bc/gov/repository/di/RepositoriesModule.kt

- fixed on boarding screen

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/AddCardOptionFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/AddOrUpdateCardViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/scanner/BarcodeScannerFragment.kt
common/src/main/java/ca/bc/gov/common/model/CreatePatientDto.kt
repository/src/main/java/ca/bc/gov/repository/model/mapper/PatientMapper.kt

-updated reordering of health passes to fix an edge case
-updated test for duplicate health passes
-updated flow in add card view model tp emit all the states

Re-ordering edge case issue resolution and UI code refactoring.

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailViewModel.kt
app/src/main/res/values/strings.xml

-added vaccine record deletion and navigation post deletion

Vaccine record deletion and navigation post deletion

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/TestRecordsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/VaccineRecordsAdapter.kt
repository/src/main/java/ca/bc/gov/repository/analytics/AnalyticsRepository.kt

-added deletion of individual records

Deletion of individual records

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailFragment.kt

-removed hard coded date format

Removed hard coded date format

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassesFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/TestRecordsAdapter.kt
common/src/main/java/ca/bc/gov/common/exceptions/MyHealthNetworkException.kt
data/src/main/java/ca/bc/gov/data/ImmunizationRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/local/dao/TestResultDao.kt
repository/src/main/java/ca/bc/gov/repository/ClearStorageRepository.kt

-added pending test results auto update feature
-updated order of test results

Retry pending test and order test results in descending order.

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/AddOrUpdateCardViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordViewModel.kt
data/src/main/java/ca/bc/gov/data/ImmunizationRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/remote/interceptor/QueueItInterceptor.kt
data/src/main/java/ca/bc/gov/data/remote/model/response/VaccineStatusResponse.kt
repository/src/main/java/ca/bc/gov/repository/FetchVaccineRecordRepository.kt

-fixed json null pointer exception

Fixed json null pointer exception

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt

-added hyperlink indeterminate test result

Added hyperlink indeterminate test result

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsFragment.kt
data/src/main/java/ca/bc/gov/data/datasource/PatientLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/model/mapper/DtoToEntityMapper.kt

- fixed crash issue

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt
data/src/main/java/ca/bc/gov/data/datasource/PatientWithVaccineRecordLocalDataSource.kt

- fixed link click event issue

- fixed all issues related to records db

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/SettingFragment.kt

-bugfix on bcsc auth flow
-code refactored on settings fragment

Bugfix on BCSC auth flow and code refactoring

---

.github/workflows/android-pr-workflow.yml
.github/workflows/android.yml
app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/manage/ManageHealthPassAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/TestResultDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailFragment.kt

- added feature to disable delete for authenticated user
- fixed test result date issue
- updated pipeline to produce separate PR & Build release process

HAPP - 489

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
common/src/main/java/ca/bc/gov/common/model/AuthenticationStatus.kt
data/schemas/ca.bc.gov.data.local.MyHealthDataBase/2.json
data/src/main/java/ca/bc/gov/data/datasource/PatientLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/local/MyHealthDataBase.kt
data/src/main/java/ca/bc/gov/data/local/converter/AuthenticationStatusTypeConverter.kt
data/src/main/java/ca/bc/gov/data/local/dao/PatientDao.kt
data/src/main/java/ca/bc/gov/data/local/entity/PatientEntity.kt
repository/src/main/java/ca/bc/gov/repository/patient/PatientRepository.kt
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedPatientDataWorker.kt

-bug fix for db migration
-code refactoring

bug fix medication

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/HiddenHealthRecordAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/PatientLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/local/dao/PatientDao.kt
data/src/main/java/ca/bc/gov/data/model/mapper/EntityToDtoMapper.kt
repository/src/main/java/ca/bc/gov/repository/bcsc/BcscAuthRepo.kt
repository/src/main/java/ca/bc/gov/repository/di/RepositoriesModule.kt
repository/src/main/java/ca/bc/gov/repository/patient/PatientRepository.kt

-added logic to show non-bcsc records
-bug fix to show correct order of health records
-bug fix to differentiate bcsc and non-bcsc health record
-updated bcsc auth flow for access token expired user
-updated strings.xml
-added delete bcsc authenticated patient data post logout

Login again post session expiry and merge unauthenticated records post BCSC login

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/res/layout/item_medication_detail_directions.xml

-updated individual health records to avoid login check during pop backstack
-bug fix HAPP-535 to show the title on medication details screen
-updated medication details screen to show directions

HAPP-535 and HAPP-536

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/TestResultDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/res/layout/fragment_single_test_result.xml
common/src/main/java/ca/bc/gov/common/model/patient/PatientDto.kt
common/src/main/java/ca/bc/gov/common/model/test/TestRecordDto.kt
data/src/main/java/ca/bc/gov/data/local/dao/PatientDao.kt

-updated covid test details data fetching logic
-bug fix on scrolling of covid test details

Remove parcelable objects

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt

-updated individual records screen to fetch health records post background sync.

Observe and update update individual health records post background sync.

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/SingleTestResultFragment.kt

Bug fix HAPP-509

---

data/src/main/java/ca/bc/gov/data/datasource/remote/LaboratoryRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/LaboratoryApi.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/response/LabTestPdfResponse.kt
repository/src/main/java/ca/bc/gov/repository/labtest/LabOrderRepository.kt

-added network call for fetching pdf data of lab report

Network call for lab report PDF

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/res/layout/item_comment.xml
app/src/main/res/layout/item_comments_count.xml

-added view all comments ui
-bug fix in login flow: when there is no internet connection ui state reset was needed.

Added UI layer for viewing comments

---

README.md
app/build.gradle
repository/build.gradle

-updated readme.md
-updated dependencies

README.md update 

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/res/layout/fragment_medication_details.xml

- fixed comment title on 0 comments
- fixed space issue at bottom.

HAPP-608,609

---

data/src/main/java/ca/bc/gov/data/datasource/local/MedicationRecordLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/local/TestResultLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/local/VaccineRecordLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/local/dao/MedicationRecordDao.kt
data/src/main/java/ca/bc/gov/data/datasource/local/dao/TestResultDao.kt
data/src/main/java/ca/bc/gov/data/datasource/local/dao/VaccineRecordDao.kt
repository/src/main/java/ca/bc/gov/repository/FetchTestResultRepository.kt
repository/src/main/java/ca/bc/gov/repository/MedicationRecordRepository.kt
repository/src/main/java/ca/bc/gov/repository/PatientWithTestResultRepository.kt
repository/src/main/java/ca/bc/gov/repository/PatientWithVaccineRecordRepository.kt
repository/src/main/java/ca/bc/gov/repository/testrecord/TestResultRepository.kt
repository/src/main/java/ca/bc/gov/repository/vaccine/VaccineRecordRepository.kt

-bugfix on merging of non-bcsc records with bcsc records.

Bugfix on merging of non-bcsc records with bcsc records.

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordOptionAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsOptionsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/ProfileFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/SettingFragment.kt
app/src/main/res/layout/fragment_add_health_records.xml
app/src/main/res/layout/fragment_individual_health_record.xml
app/src/main/res/layout/item_health_record_login.xml
app/src/main/res/layout/item_health_records_abstract.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/fragment_individual_health_record_scene.xml

-updated view other member's health records: HAPP-413
-bug fix: HAPP-607

-updated view other member's health records

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt

Bugfix on merge issue

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordPlaceholderFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordPlaceholderViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/res/layout/health_record_placeholder_fragment.xml
app/src/main/res/navigation/health_records.xml

-bugfix health records navigation
-bugfix happ-620

Bug fix health records navigation

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailViewModel.kt

Bugfix happ-576

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/FetchTestRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/FetchTestRecordsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/TestResultDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailFragment.kt
app/src/main/res/navigation/health_records.xml
repository/src/main/java/ca/bc/gov/repository/FetchTestResultRepository.kt
repository/src/main/java/ca/bc/gov/repository/PatientWithTestResultRepository.kt

-updated add records for other users

-updated add records for other users

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/res/drawable/ic_done.xml
app/src/main/res/layout/fragment_individual_health_record.xml
app/src/main/res/xml/fragment_individual_health_record_scene.xml

Bugfix happ-621

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/protectiveword/ProtectiveWordFragment.kt
app/src/main/res/layout/fragment_protective_word.xml
app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/remote/interceptor/QueueItInterceptor.kt

-updated text as per HAPP-652
-updated keyboard configuration

Text update on protective word screen

---

app/src/main/java/ca/bc/gov/bchealth/ui/onboarding/EducationalScreenAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/onboarding/EducationalScreenFragment.kt
app/src/main/res/menu/bottom_nav_menu.xml

Retire news feed feature

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt

-bugfix: show hidden medication widget only for bcsc user

Bugfix: show hidden medication widget only for bcsc user

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/FilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/FilterViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/res/layout/fragment_individual_health_record.xml

HAPP- 693 - Don't apply filters automatically after login
HAPP-694- Not able to reset filter by clicking X

HAPP 693 & 694 Don't apply auto filter

---

app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/local/preference/EncryptedPreferenceStorage.kt
repository/src/main/java/ca/bc/gov/repository/bcsc/BcscAuthRepo.kt
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt

-added post login integrity checks
-bugfix HAPP-695

Post login integrity checks HAPP-666

---

app/src/main/java/ca/bc/gov/bchealth/utils/DatePickerHelper.kt

HAPP-696-Not able to remove date after applying a date as filter

HAPP-696-implemented clear date flow

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/FilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/FilterViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt

combined both filter and date update methods

HAPP-711-Display no records found screen when there is no records found for a applied filter

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt

HAPP-707 After applying filter records should get displayed chronological order

---

app/build.gradle

- updated version code for the release

Release 1.0.0-13

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
repository/src/main/java/ca/bc/gov/repository/patient/PatientRepository.kt

Bugfix happ-668

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/res/layout/item_health_records_abstract.xml
data/src/main/java/ca/bc/gov/data/datasource/local/preference/EncryptedPreferenceStorage.kt
repository/src/main/java/ca/bc/gov/repository/OnBoardingRepository.kt

- fixed issue of BCSC login not prompted after app is being killed from Biometric screen.

Regression Bug Fix

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/res/drawable/ic_federal_pass_forward_arrow.xml
app/src/main/res/layout/scene_mycards_single_card.xml
app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/remote/ImmunizationRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/interceptor/QueueItInterceptor.kt

-bugfix to show incorrect PHN error
-bugfix to clear filter selection for non bcsc user records
-bugfix to stop loader on non bcsc pending c-19 record
-update on ui of health pass fragment
-bugfix to show age restriction dialog only once.
-updated right angle icon

Regression bug fixes 11 to 21

---

app/src/main/res/layout/fragment_add_card_options.xml
app/src/main/res/layout/scene_mycards_add_card.xml

HAPP - 233 Make the screen responsive to mobile device screen

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/add/AddHealthRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/ProfileFragment.kt
app/src/main/res/layout/fragment_individual_health_record.xml
app/src/main/res/xml/fragment_individual_health_record_scene.xml
data/src/main/java/ca/bc/gov/data/datasource/local/preference/EncryptedPreferenceStorage.kt
repository/src/main/java/ca/bc/gov/repository/bcsc/BcscAuthRepo.kt

Bugfix happ-642

---

app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/setting/ProfileFragment.kt
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt

-bugfix to show bcsc user details soon after login

Bugfix to show bcsc user details soon after login

---

app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/CommentsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/res/drawable/ic_comment_options.xml
app/src/main/res/layout/fragment_comments.xml
app/src/main/res/layout/item_comment_with_options.xml
app/src/main/res/navigation/health_records.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
common/src/main/java/ca/bc/gov/common/utils/DateTimeExtenstions.kt

-added show all comments screen
-bugfix on number of comments text display

Show all comments + bugfix

---

common/src/main/java/ca/bc/gov/common/utils/DateTimeExtenstions.kt

-bugfix to show localised time

Bugfix to show localised time

---

README.md
app/build.gradle
app/src/main/res/values/strings.xml
common/src/main/res/values/strings.xml

Updated app name

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordsViewModel.kt
app/src/main/res/layout/item_health_record_header.xml

Icon update on health records box view depending on the login session status

---

app/src/main/res/layout/add_comment.xml

- show character counter in comment input field
- trim text to 1000 characters

HAPP 749 Block users from Adding comment with more than 1000 characters

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/HealthRecordsAdapter.kt
common/src/main/java/ca/bc/gov/common/utils/DateTimeExtenstions.kt

Bugfix happ-748: Update the timeline view for immunisation

---

common/src/main/java/ca/bc/gov/common/utils/DateTimeExtenstions.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt

-bugfix happ-761

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultViewModel.kt
app/src/main/res/layout/fragment_single_test_result.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
repository/src/main/java/ca/bc/gov/repository/di/RepositoriesModule.kt
repository/src/main/java/ca/bc/gov/repository/testrecord/CovidOrderRepository.kt

-added view pdf for c-19 reports

Added view pdf for c-19 reports

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt

Bugfix happ-802

---

app/src/main/res/values/strings.xml

Updated texts happ-804

---

repository/src/main/java/ca/bc/gov/repository/qr/ProcessQrRepository.kt

Bugfix happ-830

---

app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthInfoFragment.kt
app/src/main/res/layout/fragment_bcsc_auth_info.xml
app/src/main/res/values/configs.xml
app/src/main/res/values/strings.xml

-added play store redirection happ-777

-added play store redirection happ-777

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt

-bugfix happ-799

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultDetailsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultFragment.kt
repository/src/main/java/ca/bc/gov/repository/di/RepositoriesModule.kt
repository/src/main/java/ca/bc/gov/repository/testrecord/CovidOrderRepository.kt

-added pdf download button to c-19 test

Added pdf download button to c-19 test

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailViewModel.kt
common/src/main/java/ca/bc/gov/common/model/labtest/LabOrderDto.kt
data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/1.json
data/src/main/java/ca/bc/gov/data/datasource/local/converter/DateTimeConverter.kt
data/src/main/java/ca/bc/gov/data/datasource/local/entity/labtest/LabOrderEntity.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/ImmunizationRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/LaboratoryRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/MedicationRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/labtest/LabTestOrder.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt

-updated health records insertion during refresh
-updated collectionDateTime field to nullable as per the specs

Updated health records insertion during refresh: happ-831

---

repository/build.gradle
repository/src/main/java/ca/bc/gov/repository/bcsc/BcscAuthRepo.kt

Updated bcsc auth configurations for PROD testing. This will be configured depending on the environment variable once PROD integration testing is successful.

-updated bcsc auth configurations for PROD testing

---

data/src/main/java/ca/bc/gov/data/datasource/remote/interceptor/QueueItInterceptor.kt

-updated response handling to accept the cached records from hg happ-511

Updated response handling to accept the cached records from hg happ-511

---

app/src/main/java/ca/bc/gov/bchealth/utils/DatePickerHelper.kt
app/src/main/res/layout/fragment_fetch_vaccine_record.xml

-updated date picker to disable cursor edit happ-816

Updated date picker to disable cursor edit happ-816

---

repository/src/main/java/ca/bc/gov/repository/bcsc/BcscAuthRepo.kt

-updated session check logic to use access token expiry happ-864

Updated session check logic to use access token expiry happ-864

---

app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchFederalTravelPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Extensions.kt
app/src/main/res/values/strings.xml
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt

Added maintenance message display.

-added maintenance message display happ-809

---

app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt

-updated queueIt exception handling.
-bugfix happ-880

Bugfix happ-880 + updated queueIt exception handling.

---

app/src/main/res/values/strings.xml

Updated service down message

---

app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/tos/TermsOfServiceFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/tos/TermsOfServiceViewModel.kt
common/src/main/java/ca/bc/gov/common/model/TermsOfServiceDto.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/ProfileRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/profile/UserProfile.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt
repository/src/main/java/ca/bc/gov/repository/ProfileRepository.kt
repository/src/main/java/ca/bc/gov/repository/TermsOfServiceRepository.kt

-added termsOdServiceId in the request parameter of accepting t&s HAPP-902

Added termsOdServiceId in the request parameter of accepting t&s HAPP-902

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/res/values/strings.xml

-bugfix to PIN or DIN in the medication details : happ-932

-bugfix : happ-932

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailFragment.kt

-bugfix to control pdf download icon visibility in lab test details: happ-935

-bugfix : happ-935

---

app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/widget/AddCommentLayout.kt
app/src/main/res/layout/add_comment.xml
app/src/main/res/layout/fragment_comments.xml
app/src/main/res/layout/fragment_medication_details.xml
app/src/main/res/values/strings.xml

-added custom ui for adding comment.
-added character count error while adding comment

-added custom ui for adding comment.

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthvisits/HealthVisitDetailFragment.kt
app/src/main/res/values/strings.xml

-added faq link for health visits: happ-887

Added faq link for health visits: happ-887

---

data/build.gradle
data/src/main/java/ca/bc/gov/data/di/HealthGateWayApiModule.kt
repository/build.gradle

-updated staging env config to have queue-it enabled.

Update staging env config

---

.gitignore
README.md

Updates **README.md** file documenting the basic project configuration.

refactor: Document token generation

---

.github/workflows/android.yml
app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultFragment.kt
app/src/main/res/values/configs.xml

Applies hotfixes: HAPP-995 and HAPP-998

Syncs develop with releases

---

app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/HealthPassesFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/AddCardOptionFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/add/FetchVaccineRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthpass/manage/ManageHealthPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/FilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/immunization/ImmunizationRecordDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/vaccine/VaccineRecordDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/newsfeed/NewsfeedFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/scanner/BarcodeScannerFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/travelpass/FetchFederalTravelPassFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/FragmentExtensions.kt
common/build.gradle
data/build.gradle
gradle/wrapper/gradle-wrapper.properties
repository/build.gradle
scripts/versions.gradle

- Upgrades hilt and navigation
- Imports compose plugin lib and theme
- Handles non-exhaustive 'when' as required by kotlin upgrade

Adds compose dependency

---

app/src/main/java/ca/bc/gov/bchealth/ui/dependents/registration/AddDependentFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/UiExtensions.kt
app/src/main/res/layout/fragment_add_dependent.xml
app/src/main/res/values/strings.xml

HAPP-1155: Display checkbox error state
HAPP-1157: Trim first and last name
HAPP-1154: Fix placeholders

Fixes dependent registration UI

---

app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/ui/dependents/DependentsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/dependents/registration/AddDependentsViewModel.kt
app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/local/DependentsLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/local/dao/DependentDao.kt
repository/src/main/java/ca/bc/gov/repository/DependentsRepository.kt

HAPP-1154: Fix dependents UI issue
HAPP-1165: Display duplicate error

Dependent registration fixes

---

app/build.gradle
scripts/versions.gradle

Rollbacks lib to propagate session status to all tabs

HAPP-1153: Rollbacks navigation upgrade

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
app/src/main/java/ca/bc/gov/bchealth/SplashActivity.kt
app/src/main/java/ca/bc/gov/bchealth/SplashViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/inappupdate/InAppUpdateActivity.kt
app/src/main/res/layout/activity_in_app_update.xml
app/src/main/res/values/strings.xml
common/build.gradle
data/build.gradle
data/src/main/java/ca/bc/gov/data/datasource/remote/MobileConfigRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/HealthGatewayMobileConfigApi.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/response/MobileConfigurationResponse.kt
repository/build.gradle
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt
repository/src/main/java/ca/bc/gov/repository/worker/MobileConfigRepository.kt
scripts/versions.gradle

- As a user, I should be shown a pop-up after the splash screen informing me of an updated version of the application being available when localApiVersion is lower than remoteApiVersion

HAPP-1166: Implements force update

---

.github/workflows/android.yml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
app/src/main/java/ca/bc/gov/bchealth/SplashActivity.kt
app/src/main/java/ca/bc/gov/bchealth/SplashViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/inappupdate/InAppUpdateActivity.kt
app/src/main/res/layout/activity_in_app_update.xml
app/src/main/res/values/strings.xml
common/build.gradle
data/build.gradle
data/src/main/java/ca/bc/gov/data/datasource/remote/MobileConfigRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/HealthGatewayMobileConfigApi.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/response/MobileConfigurationResponse.kt
repository/build.gradle
repository/src/main/java/ca/bc/gov/repository/worker/FetchAuthenticatedHealthRecordsWorker.kt
repository/src/main/java/ca/bc/gov/repository/worker/MobileConfigRepository.kt
scripts/versions.gradle

Syncs develop with main branch, adding the force update feature

Back merge main: Adds force update to develop

---

app/src/main/res/values/strings.xml
data/src/main/java/ca/bc/gov/data/datasource/local/dao/DependentDao.kt

HAPP-1226: Fix DependentRegistration terms format
HAPP-1229: Fix dep registration duplication check

Dependent registration fix

---

app/src/main/java/ca/bc/gov/bchealth/ui/BaseFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/BaseRecordDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/covidtests/CovidTestResultViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/utils/NestedScrollViewExtensions.kt
app/src/main/java/ca/bc/gov/bchealth/utils/RecyclerViewExtensions.kt
app/src/main/res/layout/fragment_single_test_result.xml
scripts/versions.gradle

HAPP-927: View comments for covid test
HAPP-928:  Add comments for COVID-19 Test

HAPP-927 & HAPP-928: Comments for covid test

---

.github/workflows/android.yml
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/specialauthority/SpecialAuthorityAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/specialauthority/SpecialAuthorityDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/specialauthority/SpecialAuthorityDetailViewModel.kt
app/src/main/res/layout/fragment_special_authority_detail.xml

HAPP-925: View comments
HAPP-926: Add comments

HAPP-925 & HAPP-926: Comments for special authority

---

app/src/main/java/ca/bc/gov/bchealth/ui/dependents/records/DependentRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/dependents/records/DependentRecordsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordViewModel.kt
scripts/versions.gradle

HAPP-1404-Internet-Error-Handling
- fixed intenert connection error handling
- updated version to v.1.7.0-142

HAPP-1404-Internet-errorhandling

---

app/src/main/java/ca/bc/gov/bchealth/ui/dependents/records/DependentRecordsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/individual/IndividualHealthRecordFragment.kt
common/build.gradle
scripts/versions.gradle

added flag for manual refresh feature.

Flag for manual refresh

---

app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
app/src/main/java/ca/bc/gov/bchealth/ui/inappupdate/InAppUpdateActivity.kt
app/src/main/java/ca/bc/gov/bchealth/utils/InAppUpdateHelper.kt
app/src/main/res/values/strings.xml
scripts/versions.gradle

- added softupdate handling
- update hard update code

HAPP-1167, 1197 soft update

---

app/src/main/java/ca/bc/gov/bchealth/MainActivity.kt
app/src/main/java/ca/bc/gov/bchealth/utils/InAppUpdateHelper.kt
scripts/versions.gradle

- fixed multiple soft update prompt.

HAPP-1419 For for soft update

---

app/build.gradle
common/build.gradle
scripts/versions.gradle

> merge back release_candidate

Upgrades libs targeting 12

---

app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
common/src/main/java/ca/bc/gov/common/model/patient/PatientDto.kt
common/src/main/java/ca/bc/gov/common/model/patient/PatientNameDto.kt
data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/9.json
data/src/main/java/ca/bc/gov/data/datasource/local/MyHealthDataBase.kt
data/src/main/java/ca/bc/gov/data/datasource/local/converter/PatientNameConverter.kt
data/src/main/java/ca/bc/gov/data/datasource/local/entity/PatientEntity.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/PatientRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/HealthGatewayPrivateApi.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/interceptor/RetryInterceptor.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/ApiError.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/ApiWarning.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/patient/PatientName.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/patient/PatientPayload.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/response/PatientResponse.kt
data/src/main/java/ca/bc/gov/data/model/mapper/DtoToEntityMapper.kt
data/src/main/java/ca/bc/gov/data/model/mapper/EntityToDtoMapper.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt
data/src/main/java/ca/bc/gov/data/utils/Extensions.kt
repository/src/main/java/ca/bc/gov/repository/PatientWithBCSCLoginRepository.kt
scripts/versions.gradle

HAPP-1438 & Happ1439

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/BaseRecordDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/clinicaldocument/ClinicalDocumentDetailUI.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/labtest/LabTestDetailViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/error/BcscAuthErrorUI.kt
app/src/main/res/layout/fragment_lab_test_detail.xml
scripts/versions.gradle

- HAPP-1480: Fix button colours
- HAPP-1478: Fix loader issue
- HAPP-1479: Map 'Pending' result response

HAPP-1478, HAPP-1479, HAPP-1480: Regression fixes

---

.github/workflows/android-develop-pr-workflow.yml

- added spotless check
- added assembleDebug command

- removed clean build

---

app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationsFragment.kt
app/src/main/res/values/strings.xml

- updated recommendation screen UI

HAPP-1248 : Recommendation Immunization screen UI

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailViewModel.kt
scripts/versions.gradle

- removed body part & facility field from diagnostic imaging

HAPP-1631: remove fields from diagnostic imaging detail

---

app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationItemUI.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationsFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationsViewModel.kt

- fixed click to expand issue
- fixed color of the count issue
- fixed ordering issue
- fixed title center issue on tool bar.

HAPP-1645,1646,1647: Recommendations Fixes

---

app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationDetailItemUI.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationItemUI.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationsViewModel.kt
data/src/main/java/ca/bc/gov/data/model/mapper/EntityToDtoMapper.kt

- removed icon from the title
- fixed issue with order by date

HAPP-1647: ui issues fixes

---

app/src/main/java/ca/bc/gov/bchealth/SplashViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/HomeViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/RemoveQuickAccessTileBottomSheetFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/RemoveQuickAccessTileBottomSheetScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/RemoveQuickAccessTileViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/home/manage/QuickAccessManagementViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
app/src/main/res/navigation/home.xml
common/src/main/java/ca/bc/gov/common/model/QuickAccessLinkName.kt
common/src/main/java/ca/bc/gov/common/model/QuickAccessTileShowAsQuickLinkDto.kt
data/src/main/java/ca/bc/gov/data/datasource/local/QuickActionTileLocalDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/local/dao/QuickAccessTileDao.kt
data/src/main/java/ca/bc/gov/data/datasource/local/entity/settings/QuickAccessTileShowAsQuickLinkEntity.kt
data/src/main/java/ca/bc/gov/data/model/mapper/DtoToEntityMapper.kt
repository/src/main/java/ca/bc/gov/repository/settings/QuickAccessTileRepository.kt

- added feature to remove tile from the home screen
- added ability to manage tiles from manage tile option
- added local tile management feature

HAPP-1644,1538

---

.github/workflows/android-develop-pr-workflow.yml
app/build.gradle
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/login/BcscAuthViewModel.kt
appauth/build.gradle
common/build.gradle
common/src/main/java/ca/bc/gov/common/model/userprofile/UserProfileDto.kt
data/build.gradle
data/src/main/java/ca/bc/gov/data/datasource/remote/UserProfileRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/HealthGatewayPrivateApi.kt
data/src/main/java/ca/bc/gov/data/model/mapper/EntityToDtoMapper.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt
preference/build.gradle
repository/build.gradle
repository/src/main/java/ca/bc/gov/repository/UserProfileRepository.kt
scripts/versions.gradle

- added ability to detect TNC is updated or first time acceptance
- added PUT call for TNC update in case of upgraded TNC.

HAPP-1424 TNC changes

---

app/src/main/java/ca/bc/gov/bchealth/widget/CommentInputUI.kt
common/build.gradle
scripts/versions.gradle

- updated disable comment button if no change in the comment.

HAPP-1396 disable update comment button if no change in comment

---

app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailViewModel.kt
scripts/versions.gradle

- added comments for diagnostic imaging.

HAPP-1667 Comments for Diagnostic imaging

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/utils/Constants.kt
app/src/main/res/values/strings.xml
scripts/versions.gradle

- updated di screen as par latest screen copy.

HAPP-1685 - Updated DI Screen

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailScreen.kt
scripts/versions.gradle

HAPP-1691 bug fix for DI

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/hospitalvisits/HospitalVisitDetailScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailScreen.kt
scripts/versions.gradle

HAPP-1667 DI comments issue fix

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/hospitalvisits/HospitalVisitDetailScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/imaging/DiagnosticImagingDetailScreen.kt
scripts/versions.gradle

HAPP-1667 re fix comments

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/clinicaldocument/ClinicalDocumentDetailViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/recommendations/RecommendationScreen.kt
app/src/main/res/values/strings.xml
scripts/versions.gradle

- updated text based on final copy.

HAPP-1700 Text changes

---

common/build.gradle

- added ability to add comment
- added ability to view profile
- added option for diagnostic imaging

Release 2.0.0-224

---

app/proguard-rules.pro

- added additional keep rules for prod release.

---

app/proguard-rules.pro
data/consumer-rules.pro
scripts/versions.gradle

- fixed proguard issue with R8

Hotfix 2.0.0-226

---

app/src/main/java/ca/bc/gov/bchealth/model/mapper/DtoToUIModelMapper.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailAdapter.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
app/src/main/res/layout/item_medication_outcome.xml
app/src/main/res/values/strings.xml
common/src/main/java/ca/bc/gov/common/model/MedicationSummaryDto.kt
data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/17.json
data/src/main/java/ca/bc/gov/data/datasource/local/MyHealthDataBase.kt
data/src/main/java/ca/bc/gov/data/datasource/local/entity/medication/MedicationSummaryEntity.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/base/medication/MedicationSummary.kt
data/src/main/java/ca/bc/gov/data/model/mapper/DtoToEntityMapper.kt
data/src/main/java/ca/bc/gov/data/model/mapper/EntityToDtoMapper.kt
data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt

- added option to show pharmacist assessment.

HAPP-1637 Pharmacist Assessment

---

data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/15.json
data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/16.json
data/schemas/ca.bc.gov.data.datasource.local.MyHealthDataBase/18.json
data/src/main/java/ca/bc/gov/data/datasource/local/MyHealthDataBase.kt
data/src/main/java/ca/bc/gov/data/di/MyHealthDataBaseModule.kt
scripts/versions.gradle

- fixed DB issues
- fixe login button visibility issue.

Hotfix- HAPP-1760

---

.gitignore
.idea/inspectionProfiles/ktlint.xml
app/src/main/java/ca/bc/gov/bchealth/ui/config/MobileConfigViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/dependents/records/filter/DependentFilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/dependents/records/filter/DependentFilterViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/filter/FilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/PatientFilterFragment.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/filter/PatientFilterViewModel.kt
app/src/main/java/ca/bc/gov/bchealth/usecases/records/FetchPatientDataUseCase.kt
app/src/main/java/ca/bc/gov/bchealth/workers/FetchAuthenticatedHealthRecordsWorker.kt
common/build.gradle
common/src/main/java/ca/bc/gov/common/model/config/DataSetFeatureFlag.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/PatientServicesRemoteDataSource.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/api/HealthGatewayMobileConfigApi.kt
data/src/main/java/ca/bc/gov/data/datasource/remote/model/response/MobileConfigurationResponse.kt
preference/src/main/java/ca/bc/gov/preference/EncryptedPreferenceStorage.kt
repository/src/main/java/ca/bc/gov/repository/DependentsRepository.kt
repository/src/main/java/ca/bc/gov/repository/di/RepositoriesModule.kt
repository/src/main/java/ca/bc/gov/repository/services/PatientServicesRepository.kt
repository/src/main/java/ca/bc/gov/repository/worker/MobileConfigRepository.kt

- added ability to manage featureFlag from MobileConfig API

HAPP-1751 Feature toggle

---

app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordScreen.kt
app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/HealthRecordViewModel.kt

- fixed app crash on date filter selection.

HAPP-1801 app-crash fix

---

.github/workflows/android-develop-pr-workflow.yml
.github/workflows/android.yml

- fixed cicd build signing issue.

CICD-ISSUE

---

data/src/main/java/ca/bc/gov/data/model/mapper/ResponseToDtoMapper.kt

- fixed birth date format in API fixed.

API Response Fix
